### ISSUE TITLE
no bounding boxes in the saved image

### ISSUE THREAD

**Issue by JoyceYa** [shoumikchow/bbox-visualizer#1]
Thanks for the sharing.

I used ```cv2``` to read and save a ```PNG``` image, and used the ```bbv.draw_rectangle``` to draw rectangles on this image. The code is listed below, and I found there is no bounding boxes in the saved image.

```
import cv2
import bbox_visualizer as bbv

img=cv2.imread('.\\xxx\\xx.png')
bbxes = [[ 583,  172,  620,  207], [ 599,  166,  629,  198], [1015,  193, 1241,  374], [ 739,  173,  884,  286], [ 666 , 165 , 728  ,220], [ 641 , 170 , 667 , 194]]

for bbx in bbxes:
      bbv.draw_rectangle(img, bbx)

cv2.imwrite('.\\xx\\xxxx.png', img)
```

I also found that, if I use the ```bbv.add_label()``` function for the same img and bbx, there will be labels in the saved image, but still no bounding boxes.

I'm using cv2-version-4.4, could you help me with this problem?

**Comment by shoumikchow** [comment]
The `draw_rectangle` function returns a ndarray, which is the image. You aren't assigning the returned image to anything. Your code should be:

```
img = img.copy()
for bbx in bbxes:
      img = bbv.draw_rectangle(img, bbx)
```
Hope this helped!

**Comment by JoyceYa** [comment]
@shoumikchow your method solved the problem, thanks!
