### ISSUE TITLE
[ENHANCEMENT] Is there a way to change the color of the bounding box?

### ISSUE THREAD

**Issue by isspid** [shoumikchow/bbox-visualizer#12]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I can't change the color of the bounding box.

**Describe the solution you'd like**
Possibility to change the color of the bounding box.

**Comment by martinkozle** [comment]
I can see the function `draw_rectangle` has a positional argument `bbox_color` which takes an RGB (maybe BGR) tuple.
