### ISSUE TITLE
draw_rectangle returns a new image [BUG]

### ISSUE THREAD

**Issue by martinkozle** [shoumikchow/bbox-visualizer#13]
**Describe the bug**
All of the functions modify the passed image (numpy array). While the `draw_rectangle` function creates a copy of the passed `img` called `output`, adds the rectangles to it and returns that. Therefore the examples given in the README do not in fact draw a rectangle.

**Expected behavior**
Either all functions need to return a new image, or `draw_rectangle` needs to modify the passed image.

**Version**
0.1.0

**Comment by shoumikchow** [comment]
Fixed by #18
