### ISSUE TITLE
Expand examples using jupyter notebooks

### ISSUE THREAD

**Issue by sc0v1n0** [shoumikchow/bbox-visualizer#20]
How are you @shoumikchow  ? I found your project through [Hacktoberfest2023](https://hacktoberfest-projects.vercel.app/repos/python?q=label), I liked your project I wanted to be able to contribute, initially my first contribution would be to expand the library's examples using the jupyter notebook, so anyone interested in using it can carry out a test using these examples.

I chose to rename the folder to examples, because I have a few more contributions in mind, I want to develop this for documentation along with code.

**Describe the solution you'd like**
I updated the folder name for examples, I kept your previous scripts so the user has both options. Expand the code to Jupyter notebooks showing step by step, I added some prints to show the user that it maintains the same type of data and each result also adds the box to the image.

**Comment by sc0v1n0** [comment]
Create pull request to branch dev in your project [PR](https://github.com/shoumikchow/bbox-visualizer/pull/21)

**Comment by shoumikchow** [comment]
Thanks for the contribution! Merged!
