### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by pirik3** [shoumikchow/bbox-visualizer#29]
\AppData\Local\Programs\Python\Python311\Lib\site-packages\bbox_visualizer\bbox_visualizer.py", line 34, in draw_rectangle
    output = img.copy()
             ^^^^^^^^
AttributeError: 'str' object has no attribute 'copy'

![image](https://github.com/shoumikchow/bbox-visualizer/assets/49645171/3ffad3e6-0982-408e-8973-439a56634bde)

i coulndt solve this.

`bbox=(100, 100, 200, 200)
    img = bbv.draw_rectangle(img_path, bbox)`

**Comment by shoumikchow** [comment]
You're supposed to use the image numpy array as the input, not the image path.
Please read the docs: https://bbox-visualizer.readthedocs.io/en/latest/#bbox_visualizer.bbox_visualizer.draw_rectangle
